package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/skinnykaen/rpa_clone/graph"
	"github.com/skinnykaen/rpa_clone/internal/models"
)

// CreateChat is the resolver for the CreateChat field.
func (r *mutationResolver) CreateChat(ctx context.Context, input models.NewChat) (*models.ChatMutationResult, error) {
	panic(fmt.Errorf("not implemented: CreateChat - CreateChat"))
}

// DeleteChat is the resolver for the DeleteChat field.
func (r *mutationResolver) DeleteChat(ctx context.Context, id string) (*models.Response, error) {
	panic(fmt.Errorf("not implemented: DeleteChat - DeleteChat"))
}

// Chats is the resolver for the Chats field.
func (r *queryResolver) Chats(ctx context.Context, user *string) ([]*models.ChatHTTP, error) {
	panic(fmt.Errorf("not implemented: Chats - Chats"))
}

// UserJoined is the resolver for the UserJoined field.
func (r *subscriptionResolver) UserJoined(ctx context.Context, user string, chat string) (<-chan *models.MessageHTTP, error) {
	panic(fmt.Errorf("not implemented: UserJoined - UserJoined"))
}

// Subscription returns graph.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graph.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
