package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/skinnykaen/rpa_clone/internal/models"
)

// GetCourseByID is the resolver for the GetCourseById field.
func (r *queryResolver) GetCourseByID(ctx context.Context, id string) (*models.CourseHTTP, error) {
	panic(fmt.Errorf("not implemented: GetCourseByID - GetCourseById"))
}

// GetCoursesByUser is the resolver for the GetCoursesByUser field.
func (r *queryResolver) GetCoursesByUser(ctx context.Context) (*models.CoursesListHTTP, error) {
	panic(fmt.Errorf("not implemented: GetCoursesByUser - GetCoursesByUser"))
}
