package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/skinnykaen/rpa_clone/internal/models"
)

// PostMessage is the resolver for the PostMessage field.
func (r *mutationResolver) PostMessage(ctx context.Context, input models.NewMessage) (*models.MessageHTTP, error) {
	panic(fmt.Errorf("not implemented: PostMessage - PostMessage"))
}

// DeleteMessage is the resolver for the DeleteMessage field.
func (r *mutationResolver) DeleteMessage(ctx context.Context, id string) (*models.Response, error) {
	panic(fmt.Errorf("not implemented: DeleteMessage - DeleteMessage"))
}

// MessagesFromUser is the resolver for the MessagesFromUser field.
func (r *queryResolver) MessagesFromUser(ctx context.Context, input models.MessagesFromUserInput, first *int, after *string) (*models.MessageConnection, error) {
	panic(fmt.Errorf("not implemented: MessagesFromUser - MessagesFromUser"))
}
