package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/skinnykaen/rpa_clone/internal/models"
)

// CreateParentRel is the resolver for the CreateParentRel field.
func (r *mutationResolver) CreateParentRel(ctx context.Context, parentID string, childID string) (*models.Response, error) {
	panic(fmt.Errorf("not implemented: CreateParentRel - CreateParentRel"))
}

// DeleteParentRel is the resolver for the DeleteParentRel field.
func (r *mutationResolver) DeleteParentRel(ctx context.Context, parentID string, childID string) (*models.Response, error) {
	panic(fmt.Errorf("not implemented: DeleteParentRel - DeleteParentRel"))
}

// GetChildrenByParent is the resolver for the GetChildrenByParent field.
func (r *queryResolver) GetChildrenByParent(ctx context.Context, parentID string) (*models.UsersList, error) {
	panic(fmt.Errorf("not implemented: GetChildrenByParent - GetChildrenByParent"))
}

// GetParentsByChild is the resolver for the GetParentsByChild field.
func (r *queryResolver) GetParentsByChild(ctx context.Context, childID string) (*models.UsersList, error) {
	panic(fmt.Errorf("not implemented: GetParentsByChild - GetParentsByChild"))
}
