package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	"github.com/skinnykaen/rpa_clone/internal/models"
)

// SetActivationByCode is the resolver for the SetActivationByCode field.
func (r *mutationResolver) SetActivationByCode(ctx context.Context, activationByCode bool) (*models.Response, error) {
	panic(fmt.Errorf("not implemented: SetActivationByCode - SetActivationByCode"))
}
